---
title: "Cross Validation"
author: "Christian Pascual"
date: "4/2/2019"
output: html_document
---

```{r setup, message = FALSE}
library(glmnet) # LASSO
library(mgcv) # GAMs
library(modelr) # cross-validation help

# Loading in the dataset
admit.data = read.csv(file = "./admission_predict.csv") %>% 
  janitor::clean_names() %>% 
  dplyr::mutate(
    gre.std = (gre_score - mean(gre_score)) / sd(gre_score),
    toefl.std = (toefl_score - mean(toefl_score)) / sd(toefl_score),
    cgpa.std = (cgpa - mean(cgpa)) / sd(cgpa),
    uni.rating = university_rating,
    sop.strength = sop,
    lor.strength = lor
  ) %>% 
  dplyr::select(serial_no, gre.std:lor.strength, research, chance_of_admit)
```

```{r train-test-split }
set.seed(8106)
# Set up indices for splitting between training and test datasets
folds = crossv_kfold(admit.data, k = 10)
```

```{r models }
# Set up the basic linear model
lin.fit = lm(chance_of_admit ~ gre.std + toefl.std + cgpa.std 
             + uni.rating + sop.strength + lor.strength 
             + research, data = admit.data)

# Set up the cross-validation for cv.glmnet
X = admit.data %>% dplyr::select(gre.std:research)
fmt.X = model.matrix(~ gre.std + toefl.std + cgpa.std + uni.rating + 
                   sop.strength + lor.strength + research, X)
y = admit.data$chance_of_admit

# Perform the cross-validation to find the optimal lambda
# Create the optimal LASSO fit
lasso.cv = cv.glmnet(fmt.X[,-1], y, alpha = 1, type.measure = "mse")
lasso.fit = glmnet(fmt.X[,-1], y, alpha = 1, 
                   lambda = lasso.cv$lambda.min)

# Create the GAM model
gam.fit =  gam(chance_of_admit ~ gre.std + s(toefl.std) + s(cgpa.std) 
               + uni.rating + sop.strength + lor.strength 
               + research, data = admit.data)
```



```{r}
fmt.X = model.matrix(~ gre.std + toefl.std + cgpa.std + uni.rating + 
                   sop.strength + lor.strength + research, X)
```

```{r}
# linear model
lm_models = map(folds$train, ~ lm(chance_of_admit ~ gre.std + toefl.std + cgpa.std 
             + uni.rating + sop.strength + lor.strength 
             + research, data = .))

summary(map2_dbl(lm_models, folds$test, modelr::rmse))


```

