---
title: "Tables"
author: "Dayoung Yu"
date: "4/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(mgcv)
library(glmnet)
library(earth)
library(caret)

admit.data = read.csv(file = "./admission_predict.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    gre.std = (gre_score - mean(gre_score)) / sd(gre_score),
    toefl.std = (toefl_score - mean(toefl_score)) / sd(toefl_score),
    cgpa.std = (cgpa - mean(cgpa)) / sd(cgpa),
    uni.rating = university_rating,
    sop.strength = sop,
    lor.strength = lor
  ) %>% 
  select(serial_no, gre.std:lor.strength, research, chance_of_admit)
```

```{r}
#linear model
glm.fit = glm(chance_of_admit ~ gre.std + toefl.std + cgpa.std + uni.rating + 
                   sop.strength + lor.strength + research, data = admit.data)

# create matrix
X = admit.data %>% select(gre.std:research)
fmt.X = model.matrix(~ gre.std + toefl.std + cgpa.std + uni.rating + 
                   sop.strength + lor.strength + research, X)
y = admit.data$chance_of_admit


# lasso model
lasso.cv = cv.glmnet(fmt.X[,-1], y, alpha = 1, type.measure = "mse")
lasso.fit = glmnet(fmt.X[,-1], y, alpha = 1, lambda = lasso.cv$lambda.min)


# ridge model

ridge.cv = cv.glmnet(fmt.X[,-1], y, alpha = 0, type.measure = "mse",
                       lambda = exp(seq(-1, 10, length=100)))
ridge.fit = glmnet(fmt.X[,-1], y, alpha = 0, lambda = ridge.cv$lambda.min)
  

# gamma model
gam.fit =  gam(chance_of_admit ~ gre.std + s(toefl.std) + s(cgpa.std) +
                   uni.rating + sop.strength + lor.strength + research, data = admit.data)


# mars model
tuning_grid = expand.grid(
  degree = 1:3, 
  nprune = seq(2, 50, length.out = 10) %>% floor()
  )

mars.fit = train(
    x = X,
    y = y,
    method = "earth",
    trControl = trainControl(method = "cv", number = 10),  
    tuneGrid = tuning_grid
)

```

# Make Table
```{r}
Predictor = row.names(as.tibble(coef(glm.fit))) 

glm.coef = as.tibble(coef(glm.fit)) %>%
  rownames_to_column() %>%
  select("Predictor" = rowname, "Linear" = value)

lasso.coef = as.tibble(coef(lasso.fit)[,1]) %>%
  rownames_to_column() %>%
  select("Predictor" = rowname, "LASSO" = value)

ridge.coef = as.tibble(coef(ridge.fit)[,1]) %>%
  rownames_to_column() %>%
  select("Predictor" = rowname, "Ridge" = value)
 
gam.coef = as.tibble(coef(gam.fit)[1:6]) %>%
  rownames_to_column() %>%
  select("Predictor" = rowname, "GAM" = value)

glm_lasso = full_join(glm.coef, lasso.coef, by = "Predictor")

coef.table = full_join(glm_lasso, ridge.coef, by = "Predictor") %>%
  column_to_rownames(var = "Predictor")

```

# print tables
```{r}
library(kableExtra)
options(knitr.kable.NA = '*')

coef.table %>%
kable("latex", booktabs = T, linesep = "", escape = F, digits = 4,
      caption = "Coefficient estimates of the three linear models") %>%
  kable_styling(latex_options = c("striped", "hold_position")) %>%
  add_header_above(c(" " = 1, "Coefficient Estimates" = 3), bold = T) %>%
  column_spec(-1, width = "6em")

```

